language: cpp

branches:
  only:
  - master

os:
- linux
- osx

dist: trusty
sudo: false

compiler:
- gcc
- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - cmake
    - cmake-data
    - gcc-4.9
    - g++-4.9
    - clang
    - libssl-dev
    - libusb-dev

before_install:
- uname -a
- cmake --version
- if [ "$CC" = "gcc" ]; then export CC="gcc-4.9" CXX="g++-4.9"; fi
- mkdir pok3r-build

install:
- cd pok3r-build
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CMAKE_INCLUDE_PATH='/usr/local/opt/openssl/include'; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CMAKE_LIBRARY_PATH='/usr/local/opt/openssl/lib'; fi
- cmake -D DISABLE_ZPNG=1 -D DISABLE_ZJPEG=1 -D DISABLE_ZWEBP=1 -D DISABLE_ZDATABASE=1 ..
- make pok3rtool

script:
- cd pok3rtool
- ./pok3rtool list | tee -a output
